### ISSUE TITLE
How to Compile? (Windows)

### ISSUE THREAD

**Issue by imablueperson** [pangbox/rugburn#1]
I'm sorry if this is the wrong place to ask this, but I was wondering if you'd be able to provide a guide on how to compile the ijl15.dll on a Windows machine? I have no experience with this sort of thing but would really like to be able to play Pangya. I have my private server all set up, just need a way to get the client up and running. Thank you for your time, and I'm sorry for any trouble!

**Comment by jchv** [comment]
Sorry I never replied, I was not watching the repository (accidentally.) In v1.2 we now have configuration files that make it easier to not need to make custom builds. In addition, there is now a Visual Studio project file you can use to compile it yourself on Windows without needing to set up OpenWatcom 2 or Make. Hopefully, this issue is now resolved.
